export * from './message';
export * from './lock';
export * from './user';
export * from './camera';
export * from './splash-logo';
export * from './dots';
export * from './Polygon';
export * from './coursesIcon';
export * from './home';
export * from './calendar';
export * from './search';
export * from './filter';
export * from './star';
export * from './layout';
export * from './social-share';
export * from './bookmark';
export * from './clock';
export * from './playBtnIcon';
export * from './completedMarkIcon';
export * from './booking';
export * from './fullstar';
export * from './emptystar';
export * from './play-next';
export * from './play-prev';
export * from './dots-group';
export * from './bookmark2';
export * from './save-icon';
export * from './unsave-icon';
export * from './wallet';
export * from './coupon';

export const AppleIcon = '/assets/icons/apple.png';
export const FbIcon = '/assets/icons/fb.png';
export const GoogleIcon = '/assets/icons/google.png';
